stages:
  - ci
  - publish

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  GITLAB_IMAGE_NAME: $CI_REGISTRY_IMAGE/lightning-nodes
  COMMIT_TAG: $CI_COMMIT_SHORT_SHA

cargo-fmt:
  stage: ci
  image: rustlang/rust:nightly
  script:
    - rustup component add rustfmt
    - cargo fmt --check

cargo-test:
  needs: [cargo-fmt]
  stage: ci
  image: rust:1.88
  script:
    - cargo test

publish:
  stage: publish
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    # Full: Api + Worker (latest)
    - docker build -t "$GITLAB_IMAGE_NAME:latest" .
    - docker tag "$GITLAB_IMAGE_NAME:latest" "$GITLAB_IMAGE_NAME:full"
    - docker tag "$GITLAB_IMAGE_NAME:full" "$GITLAB_IMAGE_NAME:full-$COMMIT_TAG"
    - docker push "$GITLAB_IMAGE_NAME:full"
    - docker push "$GITLAB_IMAGE_NAME:full-$COMMIT_TAG"
    - docker push "$GITLAB_IMAGE_NAME:latest"

    # Api only
    - docker build -t "$GITLAB_IMAGE_NAME:api-only" --build-arg FEATURES="disable_worker" .
    - docker push "$GITLAB_IMAGE_NAME:api-only"

    # Worker only
    - docker build -t "$GITLAB_IMAGE_NAME:worker-only" --build-arg FEATURES="disable_api" .
    - docker push "$GITLAB_IMAGE_NAME:worker-only"
  only:
    - main