stages:
  - ci
  - publish

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  GITLAB_IMAGE_NAME: $CI_REGISTRY_IMAGE/lightning-nodes
  COMMIT_TAG: $CI_COMMIT_SHORT_SHA

cargo-fmt:
  stage: ci
  image: rustlang/rust:nightly
  script:
    - rustup component add rustfmt
    - cargo fmt --check

cargo-test:
  stage: ci
  image: rust:1.88
  script:
    - cargo test

.publish-template:
  stage: publish
  image: docker:27.4.1
  services:
    - docker:27.4.1-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  only:
    - main

publish-full:
  extends: .publish-template
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build -t "$GITLAB_IMAGE_NAME:full" --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $GITLAB_IMAGE_NAME:latest .
    - docker tag "$GITLAB_IMAGE_NAME:full" "$GITLAB_IMAGE_NAME:full-$COMMIT_TAG"
    - docker push "$GITLAB_IMAGE_NAME:full"
    - docker push "$GITLAB_IMAGE_NAME:full-$COMMIT_TAG"
    - docker tag "$GITLAB_IMAGE_NAME:full" "$GITLAB_IMAGE_NAME:latest"
    - docker push "$GITLAB_IMAGE_NAME:latest"

publish-api-only:
  needs: [publish-full]
  extends: .publish-template
  script:
    - docker pull $GITLAB_IMAGE_NAME:latest
    - docker build -t "$GITLAB_IMAGE_NAME:api-only" --build-arg FEATURES="disable_api" --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $GITLAB_IMAGE_NAME:latest .
    - docker tag "$GITLAB_IMAGE_NAME:api-only" "$GITLAB_IMAGE_NAME:api-only-$COMMIT_TAG"
    - docker push "$GITLAB_IMAGE_NAME:api-only"
    - docker push "$GITLAB_IMAGE_NAME:api-only-$COMMIT_TAG"
  
publish-worker-only:
  needs: [publish-full]
  extends: .publish-template
  script:
    - docker pull $GITLAB_IMAGE_NAME:latest
    - docker build --pull -t "$GITLAB_IMAGE_NAME:worker-only" --build-arg FEATURES="disable_worker" --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $GITLAB_IMAGE_NAME:latest .
    - docker tag "$GITLAB_IMAGE_NAME:worker-only" "$GITLAB_IMAGE_NAME:worker-only-$COMMIT_TAG"
    - docker push "$GITLAB_IMAGE_NAME:worker-only"
    - docker push "$GITLAB_IMAGE_NAME:worker-only-$COMMIT_TAG"