apiVersion: v1
kind: PersistentVolume
metadata:
  name: gke-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOncePod
  gcePersistentDisk:
    pdName: disk-20250720-015557
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gke-pvc
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
