apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-api-ingress
spec:
  ingressClassName: 'gce'
  rules:
  - host: bipa.talison.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bipa-challenge-api-service
            port:
              number: 80